language: generic
dist: xenial
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 367ff54222a2
before_install:
- openssl aes-256-cbc -K $encrypted_367ff54222a2_key -iv $encrypted_367ff54222a2_iv
  -in deploy_key.enc -out deploy_key -d
