language: generic
dist: xenial
script: bash ./deploy.sh
branches:
  only:
  - master
before_install:
# Deploy key for dreamland_mudlet repository is stored as a secret env variable in Travis,
# in base64 encoding, to avoid Travis complaining about special unescaped characters.
- echo $deploy_key_base64 | base64 -d > deploy_key
- chmod 600 deploy_key
- ls -la
- eval `ssh-agent -s`
- ssh-add deploy_key
